#!/bin/sh

echo switch to the integrated deployment branch
git checkout deploy
echo sync the integrated deployment branch with the repo
git pull
echo merge the feature branch
git merge --no-ff more-readme -m "merge more readme"
echo here the merged version would be deployed
echo switch back to the feature branch
git checkout more-readme
