#!/bin/sh

set -e
set -x

# fetch the integrated deployment branch, it's head is saved as FETCH_HEAD
git fetch origin deploy
# switch to the integrated deployment branch
git checkout deploy
# merge the previously fetched contents of the integrated deployment branch
git merge FETCH_HEAD

# merge the feature branch
git merge --no-ff feature -m "merge the feature"
# here the merged version would be deployed
git push

# switch back to the feature branch
git checkout feature
